version: '3.4'
services:
  app:
    image: 'user-balance:1.0'
    ports:
      - 8080:8080
    networks:
      ub-net:
    depends_on: [ database ]

  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_LOGIN}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-ub:/var/lib/postgresql/data
    networks:
      ub-net:

  cache_redis:
    image: 'redis:6.2.6-alpine'
    ports:
      - '6379:6379'

volumes:
  db-ub:
networks:
  ub-net:
