version: '3.4'
services:
  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_LOGIN}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - './sql:/var/lib/postgresql/data'